<script setup>
import { computed, onMounted, ref } from 'vue'
import { Bar } from 'vue-chartjs'
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Tooltip, Legend } from 'chart.js'
import { ArrowDownRight, ArrowUpRight, Boxes, CircleDollarSign, ClipboardList, Info, Package, RefreshCw, ShoppingBag, Sparkles, TrendingUp } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'
import { api, endpoints, friendlyError } from '../services/api'
import { isAdmin, readSession } from '../services/session'

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend)
const admin=isAdmin(); const name=readSession()?.username || 'equipe'; const now=new Date(); const month=ref(now.getMonth()+1); const year=ref(now.getFullYear()); const loading=ref(true); const error=ref(''); const kpi=ref(null); const insights=ref([]); const sales=ref([]); const finance=ref(null)
const monthLabel=computed(()=>new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(year.value,month.value-1,1)))
const chartData=computed(()=>({labels:['Mês anterior','Mês selecionado'],datasets:[{label:'Receita',data:[Number(kpi.value?.receitaMesAnterior||0),Number(kpi.value?.receitaMes||0)],backgroundColor:['#d8ddd6','#63836f'],borderRadius:7,maxBarThickness:44}]}))
const chartOptions={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:(ctx)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(ctx.raw)}}},scales:{x:{grid:{display:false},border:{display:false},ticks:{color:'#7b827b'}},y:{beginAtZero:true,grid:{color:'#edf0eb'},border:{display:false},ticks:{color:'#7b827b',callback:(v)=>'R$ '+v}}}}
const money=(value)=>value==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)
const recentSales=computed(()=>sales.value.slice(0,5))
async function load() {
  loading.value=true; error.value=''
  const requests=[endpoints.kpis(month.value,year.value),endpoints.insights(month.value,year.value),api.get('/api/vendas')]
  if(admin) requests.push(endpoints.resumoFinanceiro(month.value,year.value))
  const results=await Promise.allSettled(requests)
  if(results[0].status==='fulfilled') kpi.value=results[0].value.data; else error.value=friendlyError(results[0].reason)
  if(results[1].status==='fulfilled') insights.value=results[1].value.data||[]
  if(results[2].status==='fulfilled') sales.value=(results[2].value.data||[]).slice()
  if(admin && results[3]?.status==='fulfilled') finance.value=results[3].value.data
  loading.value=false
}
function setPeriod(event) { if (!event.target.value) return; const [selectedYear,selectedMonth]=event.target.value.split('-'); year.value=Number(selectedYear); month.value=Number(selectedMonth); load() }
onMounted(load)
</script>

<template><AppShell><div class="page-heading"><div><span class="eyebrow">{{ admin?'PAINEL DE GESTÃO':'CENTRO DE OPERAÇÕES' }}</span><h1>{{ admin?'Visão geral':'Bem vindo' }}</h1><p>{{ admin?'Acompanhe os indicadores do negócio e o ritmo da operação.':'Acompanhe vendas, produtos e a rotina da confeitaria.' }} <span class="capitalize">{{ monthLabel }}</span></p></div><div class="heading-actions"><input class="month-input" type="month" :value="`${year}-${String(month).padStart(2,'0')}`" @change="setPeriod"/><button class="button-secondary" @click="load" :disabled="loading"><RefreshCw :size="16" :class="{spin:loading}"/> Atualizar</button></div></div>
  <div v-if="error" class="alert-banner"><Info :size="18"/><div><strong>Não foi possível carregar todos os indicadores</strong><p>{{ error }}</p></div><button class="button-text" @click="load">Tentar novamente</button></div>
  <div v-if="loading" class="dashboard-loading"><div class="skeleton-row"><i v-for="i in 4" :key="i"></i></div><div class="skeleton-wide"></div></div>
  <template v-else>
    <section v-if="admin" class="stats-grid">
      <article class="stat-card"><div class="stat-top"><span>Receita do mês</span><span class="stat-icon green"><CircleDollarSign :size="18"/></span></div><strong>{{ money(kpi?.receitaMes) }}</strong><small><ArrowUpRight :size="13"/> {{ money(kpi?.receitaMesAnterior) }} no mês anterior</small></article>
      <article class="stat-card"><div class="stat-top"><span>Vendas no período</span><span class="stat-icon blue"><ShoppingBag :size="18"/></span></div><strong>{{ kpi?.quantidadeVendas ?? '—' }}</strong><small>Conforme relatório mensal da API</small></article>
      <article class="stat-card"><div class="stat-top"><span>Ticket médio</span><span class="stat-icon violet"><TrendingUp :size="18"/></span></div><strong>{{ money(kpi?.ticketMedio) }}</strong><small>Valor médio por venda</small></article>
      <article class="stat-card"><div class="stat-top"><span>Estoque baixo</span><span class="stat-icon amber"><Boxes :size="18"/></span></div><strong>{{ kpi?.itensEstoqueBaixo ?? '—' }}</strong><small>Itens abaixo do nível mínimo</small></article>
    </section>
    <section v-else class="stats-grid operational-stats">
      <article class="stat-card"><div class="stat-top"><span>Vendas no período</span><span class="stat-icon blue"><ShoppingBag :size="18"/></span></div><strong>{{ kpi?.quantidadeVendas ?? '—' }}</strong><small>Pedidos registrados neste mês</small></article>
      <article class="stat-card"><div class="stat-top"><span>Produto em destaque</span><span class="stat-icon green"><Package :size="18"/></span></div><strong class="text-stat">{{ kpi?.topProduto || 'Sem dados' }}</strong><small>Mais vendido no período</small></article>
      <article class="stat-card"><div class="stat-top"><span>Canal principal</span><span class="stat-icon violet"><TrendingUp :size="18"/></span></div><strong class="text-stat">{{ kpi?.topCanal || 'Sem dados' }}</strong><small>Canal com maior participação</small></article>
      <article class="stat-card"><div class="stat-top"><span>Reposição necessária</span><span class="stat-icon amber"><Boxes :size="18"/></span></div><strong>{{ kpi?.itensEstoqueBaixo ?? '—' }}</strong><small>Insumos abaixo do mínimo</small></article>
    </section>
    <section v-if="admin" class="dashboard-grid"><article class="panel chart-panel"><div class="panel-heading"><div><span class="eyebrow">COMPARATIVO</span><h2>Receita por mês</h2></div><span class="panel-period">{{ year }}</span></div><div class="chart-wrap" v-if="kpi"><Bar :data="chartData" :options="chartOptions"/></div><div v-else class="empty-state compact"><TrendingUp :size="22"/><p>Nenhum dado disponível para o período.</p></div><p class="chart-note">Valores fornecidos pelo endpoint de KPIs. Não há série histórica diária disponível.</p></article>
      <article class="panel highlights-panel"><div class="panel-heading"><div><span class="eyebrow">DESTAQUES DO PERÍODO</span><h2>Visão rápida</h2></div><span class="stat-icon green"><Sparkles :size="17"/></span></div><div class="highlight-line"><span>Produto mais vendido</span><strong>{{ kpi?.topProduto || 'Sem dados' }}</strong></div><div class="highlight-line"><span>Canal em destaque</span><strong>{{ kpi?.topCanal || 'Sem dados' }}</strong></div><div class="highlight-line"><span>Margem de lucro</span><strong>{{ kpi?.margemLucro==null?'—':`${Number(kpi.margemLucro).toLocaleString('pt-BR')}%` }}</strong></div><div v-if="admin&&finance" class="highlight-line"><span>Resultado financeiro</span><strong>{{ money(finance.lucro) }}</strong></div><div class="highlight-foot"><span class="status-dot"></span> Dados consultados diretamente na API</div></article>
      <article class="panel insight-panel"><div class="panel-heading"><div><span class="eyebrow">ANÁLISE DO NEGÓCIO</span><h2>Insights do período</h2></div><Sparkles :size="17" class="muted-icon"/></div><div v-if="insights.length" class="insight-list"><div v-for="(item,index) in insights" :key="index" class="insight-row" :class="String(item.tipo||'').toLowerCase()"><span class="insight-marker"><ArrowUpRight v-if="item.tipo==='OPORTUNIDADE'" :size="15"/><ArrowDownRight v-else :size="15"/></span><div><strong>{{ item.titulo }}</strong><p>{{ item.descricao }}</p><small v-if="item.acao">Próxima ação: {{ item.acao }}</small></div></div></div><div v-else class="empty-state compact"><Sparkles :size="22"/><p>Nenhum insight disponível neste período.</p></div></article>
      <article class="panel sales-panel"><div class="panel-heading"><div><span class="eyebrow">MOVIMENTAÇÃO</span><h2>Vendas registradas</h2></div><RouterLink to="/vendas" class="button-text">Ver todas <ArrowUpRight :size="14"/></RouterLink></div><div v-if="recentSales.length" class="mini-table"><div class="mini-table-head"><span>Venda</span><span>Cliente</span><span>Status</span><span>Total</span></div><div v-for="sale in recentSales" :key="sale.id" class="mini-table-row"><strong>#{{ sale.numeroVenda ?? String(sale.id||'').slice(0,8) }}</strong><span>{{ sale.clienteNome||'Não informado' }}</span><span><i class="status-badge" :class="String(sale.status||'').toLowerCase()">{{ sale.status||'—' }}</i></span><b>{{ money(sale.total) }}</b></div></div><div v-else class="empty-state compact"><ClipboardList :size="22"/><p>Nenhuma venda encontrada.</p></div></article>
    </section>
    <section v-else class="dashboard-grid operational-dashboard"><article class="panel operations-panel"><div class="panel-heading"><div><span class="eyebrow">ACESSO RÁPIDO</span><h2>Rotina da operação</h2></div><Boxes :size="18" class="muted-icon"/></div><RouterLink to="/vendas" class="operation-link"><span class="operation-icon"><ShoppingBag :size="17"/></span><span><strong>Registrar ou consultar vendas</strong><small>Pedidos e canais de venda</small></span><ArrowUpRight :size="16"/></RouterLink><RouterLink to="/compras" class="operation-link"><span class="operation-icon"><ClipboardList :size="17"/></span><span><strong>Consultar compras</strong><small>Entradas de ingredientes</small></span><ArrowUpRight :size="16"/></RouterLink><RouterLink to="/estoque" class="operation-link"><span class="operation-icon"><Boxes :size="17"/></span><span><strong>Movimentar estoque</strong><small>Entradas e ajustes dos insumos</small></span><ArrowUpRight :size="16"/></RouterLink><RouterLink to="/produtos" class="operation-link"><span class="operation-icon"><Package :size="17"/></span><span><strong>Consultar produtos</strong><small>Catálogo disponível</small></span><ArrowUpRight :size="16"/></RouterLink></article><article class="panel sales-panel"><div class="panel-heading"><div><span class="eyebrow">MOVIMENTAÇÃO</span><h2>Vendas registradas</h2></div><RouterLink to="/vendas" class="button-text">Ver todas <ArrowUpRight :size="14"/></RouterLink></div><div v-if="recentSales.length" class="mini-table"><div class="mini-table-head"><span>Venda</span><span>Cliente</span><span>Status</span><span>Total</span></div><div v-for="sale in recentSales" :key="sale.id" class="mini-table-row"><strong>#{{ sale.numeroVenda ?? String(sale.id||'').slice(0,8) }}</strong><span>{{ sale.clienteNome||'Não informado' }}</span><span><i class="status-badge" :class="String(sale.status||'').toLowerCase()">{{ sale.status||'—' }}</i></span><b>{{ money(sale.total) }}</b></div></div><div v-else class="empty-state compact"><ClipboardList :size="22"/><p>Nenhuma venda encontrada.</p></div></article><article class="panel insight-panel"><div class="panel-heading"><div><span class="eyebrow">LEITURA DO PERÍODO</span><h2>Recomendações operacionais</h2></div><Sparkles :size="17" class="muted-icon"/></div><div v-if="insights.length" class="insight-list"><div v-for="(item,index) in insights" :key="index" class="insight-row" :class="String(item.tipo||'').toLowerCase()"><span class="insight-marker"><ArrowUpRight v-if="item.tipo==='OPORTUNIDADE'" :size="15"/><ArrowDownRight v-else :size="15"/></span><div><strong>{{ item.titulo }}</strong><p>{{ item.descricao }}</p><small v-if="item.acao">Próxima ação: {{ item.acao }}</small></div></div></div><div v-else class="empty-state compact"><Sparkles :size="22"/><p>Nenhuma recomendação disponível neste período.</p></div></article></section>
    <div v-if="!kpi&&!error" class="empty-state"><Package :size="24"/><strong>Nenhum dado disponível</strong><p>Os relatórios ainda não possuem informações para este período.</p></div>
  </template>
</AppShell></template>
