<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ArrowDown, ArrowUp, CirclePlus, Download, Search, RefreshCw, PackageOpen, SlidersHorizontal, X, Trash2, Eye, Save, LoaderCircle } from 'lucide-vue-next'
import AppShell from '../components/AppShell.vue'
import { api, endpoints, friendlyError } from '../services/api'
import { isAdmin } from '../services/session'

const props=defineProps({ moduleKey:{type:String,default:''} }); const route=useRoute(); const admin=isAdmin(); const rows=ref([]); const loading=ref(true); const error=ref(''); const search=ref(''); const modal=ref(false); const busy=ref(false); const notice=ref(''); const form=ref({}); const referenceOptions=ref({}); const page=ref(1); const pageSize=8
const configs={
  produtos:{title:'Produtos',description:'Catálogo e preços do portfólio de produção.',endpoint:endpoints.produtos,columns:[['nome','Produto'],['preco','Preço','money'],['id','Identificador','short']],canCreate:admin,canDelete:admin,fields:[['nome','Nome','text'],['descricao','Descrição','text'],['categoriaId','ID da categoria','text'],['preco','Preço','number'],['ativo','Ativo','checkbox']]},
  vendas:{title:'Vendas',description:'Acompanhe os pedidos e o desempenho dos canais.',endpoint:endpoints.vendas,columns:[['numeroVenda','Venda'],['clienteNome','Cliente'],['funcionarioNome','Atendente'],['status','Status','badge'],['total','Total','money']],canCreate:true,fields:[['clienteId','Cliente','reference','/api/clientes','nome','id'],...(admin?[['funcionarioId','Funcionário','reference','/api/funcionarios','nome','id']]:[['funcionarioId','ID do funcionário','text']]),['canal','Canal','select',['IFOOD','SITE','LOJA_FISICA','MERCADO_LIVRE']],['formaPagamento','Forma de pagamento','select',['DINHEIRO','PIX','CREDITO','DEBITO','IFOOD','MERCADO_LIVRE']],['produtoId','Produto','reference','/api/produtos','nome','id'],['quantidade','Quantidade','number'],['precoUnitario','Preço unitário','number'],['custoUnitario','Custo unitário','number'],['desconto','Desconto','number'],['taxaEntrega','Taxa de entrega','number']]},
  compras:{title:'Compras',description:'Entradas de insumos e histórico de aquisições.',endpoint:endpoints.compras,columns:[['numeroNota','Nota'],['fornecedorNome','Fornecedor'],['dataCompra','Data','date'],['total','Total','money']],canCreate:true,fields:[['fornecedorId','Fornecedor','reference','/api/fornecedores','nome','id'],['dataCompra','Data e hora','datetime-local'],['ingredienteId','Ingrediente','reference','/api/ingredientes','nome','id'],['quantidade','Quantidade','number'],['precoUnitario','Preço unitário','number']]},
  clientes:{title:'Clientes',description:'Relacionamento e histórico dos clientes.',endpoint:endpoints.clientes,columns:[['nome','Nome'],['telefone','Telefone'],['email','E-mail'],['quantidadePedidos','Pedidos'],['ativo','Situação','active']],canCreate:true,canEdit:true,canDelete:admin,fields:[['nome','Nome','text'],['telefone','Telefone','text'],['email','E-mail','email'],['endereco','Endereço','text'],['dataNascimento','Data de nascimento','date'],['observacoes','Observações','textarea']]},
  fornecedores:{title:'Fornecedores',description:'Parceiros de fornecimento e contato.',endpoint:endpoints.fornecedores,columns:[['nome','Fornecedor'],['telefone','Telefone'],['email','E-mail'],['cnpj','CNPJ'],['ativo','Situação','active']],canCreate:admin,canEdit:admin,canDelete:admin,fields:[['nome','Nome','text'],['telefone','Telefone','text'],['email','E-mail','email'],['endereco','Endereço','text'],['cnpj','CNPJ','text'],['observacoes','Observações','textarea'],['ativo','Ativo','checkbox']]},
  categorias:{title:'Categorias',description:'Organize o cadastro de produtos.',endpoint:endpoints.categorias,columns:[['nome','Categoria'],['descricao','Descrição'],['ativo','Situação','active']],canCreate:admin,canEdit:admin,canDelete:admin,fields:[['nome','Nome','text'],['descricao','Descrição','text'],['ativo','Ativo','checkbox']]},
  ingredientes:{title:'Ingredientes',description:'Insumos, unidades e níveis de estoque mínimo.',endpoint:endpoints.ingredientes,columns:[['nome','Ingrediente'],['unidade','Unidade'],['custoUnitario','Custo unitário','money'],['estoqueAtual','Estoque atual'],['estoqueMinimo','Mínimo']],canCreate:admin,canEdit:admin,canDelete:admin,query:true,fields:[['nome','Nome','text'],['unidade','Unidade','select',['KG','G','L','ML','UN']],['custoUnitario','Custo unitário','number'],['estoqueAtual','Estoque atual','number'],['estoqueMinimo','Estoque mínimo','number'],['fornecedorId','Fornecedor','reference','/api/fornecedores','nome','id']]},
  receitas:{title:'Receitas',description:'Ficha técnica e consumo de ingredientes por produto.',endpoint:endpoints.receitas,columns:[['produto','Produto','nested'],['ingrediente','Ingrediente','nested'],['quantidade','Quantidade'],['unidade','Unidade']],canCreate:admin,canEdit:admin,canDelete:admin,query:true,fields:[['produtoId','Produto','reference','/api/produtos','nome','id'],['ingredienteId','Ingrediente','reference','/api/ingredientes','nome','id'],['quantidade','Quantidade','number'],['unidade','Unidade','select',['KG','G','L','ML','UN']]]},
  estoque:{title:'Movimentações de estoque',description:'Entradas e saídas registradas para controle dos insumos.',endpoint:endpoints.movimentacoes,columns:[['tipo','Movimento','badge'],['ingrediente','Ingrediente','nested'],['quantidade','Quantidade'],['createdAt','Data','date'],['observacao','Observação']],canCreate:true,fields:[['ingredienteId','Ingrediente','reference','/api/ingredientes','nome','id'],['tipo','Tipo','select',['ENTRADA','SAIDA','AJUSTE','PRODUCAO']],['quantidade','Quantidade','number'],['observacao','Observação','text']]},
  financeiro:{title:'Financeiro',description:'Lançamentos do período e resumo financeiro.',endpoint:(mes,ano)=>endpoints.financeiro(mes,ano),columns:[['dataLancamento','Data','date'],['tipo','Tipo','badge'],['categoria','Categoria'],['descricao','Descrição'],['valor','Valor','money'],['pago','Pago','active']],canCreate:admin,adminOnly:true,fields:[['tipo','Tipo','select',['RECEITA','DESPESA']],['categoria','Categoria','text'],['descricao','Descrição','text'],['valor','Valor','number'],['dataLancamento','Data','date']]},
  funcionarios:{title:'Funcionários',description:'Cadastro interno da equipe e funções.',endpoint:endpoints.funcionarios,columns:[['nome','Nome'],['email','E-mail'],['telefone','Telefone'],['papel','Função'],['ativo','Ativo','active']],canCreate:admin,canEdit:admin,canDelete:admin,adminOnly:true,fields:[['nome','Nome','text'],['email','E-mail','email'],['telefone','Telefone','text'],['papel','Função','select',['ADMIN','CAIXA','COZINHEIRA']],['salario','Salário','number'],['ativo','Ativo','checkbox']]},
}
const config=computed(()=>configs[props.moduleKey]||configs[route.params.module]||configs.produtos)
const visibleRows=computed(()=>{const term=search.value.trim().toLocaleLowerCase('pt-BR');return rows.value.filter(row=>!term||Object.values(row||{}).some(value=>String(value??'').toLocaleLowerCase('pt-BR').includes(term)))})
const pages=computed(()=>Math.max(1,Math.ceil(visibleRows.value.length/pageSize)))
const pagedRows=computed(()=>visibleRows.value.slice((page.value-1)*pageSize,page.value*pageSize))
const endpointArgs=computed(()=>[nowMonth(),nowYear()]); function nowMonth(){return new Date().getMonth()+1} function nowYear(){return new Date().getFullYear()}
function display(row,key,type){let val=row?.[key]; if(type==='nested') return val?.nome||val?.name||'—'; if(type==='money') return val==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(val);if(type==='date'&&val) return new Date(val).toLocaleDateString('pt-BR');if(type==='active') return val==null?'—':val?'Ativo':'Inativo';if(type==='short'&&val)return String(val).slice(0,8);return val??'—'}
async function load(){loading.value=true;error.value='';try{const response= config.value.adminOnly&&!admin ? {data:[]} : config.value.endpoint(...endpointArgs.value);const result=await response;const data=Array.isArray(result.data)?result.data:[];rows.value=props.moduleKey==='funcionarios'?data.map(({senha,...safe})=>safe):data}catch(e){error.value=friendlyError(e)}finally{loading.value=false}}
async function loadReferences(){const fields=(config.value.fields||[]).filter(field=>field[2]==='reference');const result=await Promise.allSettled(fields.map(field=>api.get(field[3])));const next={...referenceOptions.value};result.forEach((response,index)=>{if(response.status==='fulfilled')next[fields[index][0]]=response.value.data||[];else error.value=friendlyError(response.reason)});referenceOptions.value=next}
async function openCreate(){form.value={};for(const [key,,type] of config.value.fields||[]){if(type==='checkbox')form.value[key]=true};modal.value=true;await loadReferences()}
async function openEdit(row){const values={...row};if(values.fornecedor?.id)values.fornecedorId=values.fornecedor.id;if(values.produto?.id)values.produtoId=values.produto.id;if(values.ingrediente?.id)values.ingredienteId=values.ingrediente.id;delete values.senha;form.value=values;modal.value=true;await loadReferences()}
async function save(){if(busy.value)return;busy.value=true;error.value='';try{
  if(config.value.adminOnly&&!admin) return
  if(props.moduleKey==='vendas'&&(!form.value.clienteId||!form.value.funcionarioId)){error.value='A API exige um cliente e um funcionário vinculados à venda.';return}
  if(props.moduleKey==='vendas'&&(!form.value.produtoId||!(Number(form.value.quantidade)>0)||!(Number(form.value.precoUnitario)>0)||form.value.custoUnitario===''||form.value.custoUnitario===undefined)){error.value='Informe produto, quantidade, preço unitário e custo unitário da venda.';return}
  if(props.moduleKey==='compras'&&(!form.value.fornecedorId||!form.value.ingredienteId||!(Number(form.value.quantidade)>0)||!(Number(form.value.precoUnitario)>0))){error.value='Informe fornecedor, ingrediente, quantidade e preço unitário da compra.';return}
  let result
  if(config.value.query){const {id,...data}=form.value;const params=Object.fromEntries(Object.entries(data).filter(([,value])=>value!==''&&value!==null&&value!==undefined));result=id?await api.put(`${pathFor(props.moduleKey)}/${id}`,null,{params}):await api.post(pathFor(props.moduleKey),null,{params})}
  else if(props.moduleKey==='vendas'){const body={clienteId:form.value.clienteId,funcionarioId:form.value.funcionarioId,canal:form.value.canal,formaPagamento:form.value.formaPagamento,itens:[{produtoId:form.value.produtoId,quantidade:Number(form.value.quantidade),precoUnitario:Number(form.value.precoUnitario),custoUnitario:Number(form.value.custoUnitario)}],desconto:Number(form.value.desconto||0),taxaEntrega:Number(form.value.taxaEntrega||0)};result=await api.post('/api/vendas',body)}
  else if(props.moduleKey==='compras'){const body={fornecedorId:form.value.fornecedorId,dataCompra:form.value.dataCompra||new Date().toISOString().slice(0,16),itens:[{ingredienteId:form.value.ingredienteId,quantidade:Number(form.value.quantidade),precoUnitario:Number(form.value.precoUnitario)}]};result=await api.post('/api/compras',body)}
  else if(props.moduleKey==='estoque'){const body={ingrediente:{id:form.value.ingredienteId},tipo:form.value.tipo,quantidade:Number(form.value.quantidade),observacao:form.value.observacao||null};result=await api.post('/api/movimentacoes-estoque',body)}
  else if(config.value.query){result=await api.post(pathFor(props.moduleKey),null,{params:form.value})}
  else if(form.value.id) result=await api.put(`${pathFor(props.moduleKey)}/${form.value.id}`,form.value)
  else result=await api.post(pathFor(props.moduleKey),form.value)
  modal.value=false;notice.value='Registro salvo com sucesso.';load()
  }catch(e){error.value=friendlyError(e)}finally{busy.value=false}}
function pathFor(key){return ({produtos:'/api/produtos',clientes:'/api/clientes',fornecedores:'/api/fornecedores',categorias:'/api/categorias',ingredientes:'/api/ingredientes',receitas:'/api/receitas',estoque:'/api/movimentacoes-estoque',financeiro:'/api/lancamentos-financeiros',funcionarios:'/api/funcionarios'})[key]}
async function remove(row){if(!confirm('Deseja excluir este registro? Esta ação não pode ser desfeita.'))return;try{await api.delete(`${pathFor(props.moduleKey)}/${row.id}`);await load()}catch(e){error.value=friendlyError(e)}}
function exportCsv(){const csv=[config.value.columns.map(c=>c[1]).join(';'),...visibleRows.value.map(row=>config.value.columns.map(col=>`"${String(display(row,col[0],col[2])).replaceAll('"','""')}"`).join(';'))].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));link.download=`${props.moduleKey||'dados'}.csv`;link.click();URL.revokeObjectURL(link.href)}
watch(()=>props.moduleKey,()=>{rows.value=[];page.value=1;load()});watch(search,()=>page.value=1);onMounted(load)
</script>

<template><AppShell><div class="page-heading"><div><span class="eyebrow">{{ config.adminOnly?'CONTROLE ADMINISTRATIVO':'MÓDULO OPERACIONAL' }}</span><h1>{{ config.title }}</h1><p>{{ config.description }}</p></div><div class="heading-actions"><button class="button-secondary" @click="load" :disabled="loading"><RefreshCw :size="16" :class="{spin:loading}"/> Atualizar</button><button v-if="config.canCreate" class="button-primary" @click="openCreate"><CirclePlus :size="17"/> Novo registro</button></div></div>
<div v-if="notice" class="success-banner">{{ notice }} <button @click="notice=''" aria-label="Fechar"><X :size="15"/></button></div><div v-if="error" class="alert-banner"><PackageOpen :size="18"/><div><strong>Não foi possível concluir a consulta</strong><p>{{ error }}</p></div><button class="button-text" @click="load">Tentar novamente</button></div>
<section class="panel data-panel"><div class="table-toolbar"><div class="table-count"><strong>{{ visibleRows.length }}</strong><span> registros encontrados</span></div><div class="table-tools"><label class="search-box"><Search :size="16"/><input v-model="search" placeholder="Buscar neste módulo…"/></label><button class="button-quiet" @click="exportCsv" :disabled="!rows.length"><Download :size="16"/><span>Exportar</span></button><button class="button-quiet filter-disabled" title="Filtros disponíveis conforme campos retornados pela API"><SlidersHorizontal :size="16"/></button></div></div>
<div v-if="loading" class="table-loading"><div v-for="i in 6" :key="i"></div></div><div v-else-if="!pagedRows.length" class="empty-state"><PackageOpen :size="27"/><strong>{{ search?'Nenhum resultado para esta busca':'Nenhum dado disponível' }}</strong><p>{{ search?'Tente outro termo.':'Quando a API retornar registros, eles aparecerão aqui.' }}</p><button v-if="config.canCreate&&!search" class="button-secondary" @click="openCreate"><CirclePlus :size="16"/> Criar primeiro registro</button></div>
<div v-else class="table-scroll"><table class="data-table"><thead><tr><th v-for="column in config.columns" :key="column[0]">{{ column[1] }}</th><th v-if="config.canEdit||config.canDelete">Ações</th></tr></thead><tbody><tr v-for="row in pagedRows" :key="row.id||row.numeroVenda"><td v-for="column in config.columns" :key="column[0]"><span v-if="column[2]==='badge'" class="table-badge">{{ display(row,column[0],column[2]) }}</span><span v-else-if="column[2]==='active'" class="table-active" :class="{inactive:!row[column[0]]}"><i></i>{{ display(row,column[0],column[2]) }}</span><span v-else :class="{'money-cell':column[2]==='money'}">{{ display(row,column[0],column[2]) }}</span></td><td v-if="config.canEdit||config.canDelete"><div class="row-actions"><button v-if="config.canEdit" class="icon-button" @click="openEdit(row)" title="Editar"><Eye :size="15"/></button><button v-if="config.canDelete" class="icon-button danger-icon" @click="remove(row)" title="Excluir"><Trash2 :size="15"/></button></div></td></tr></tbody></table></div>
<div v-if="!loading&&visibleRows.length" class="table-pagination"><span>Mostrando {{ (page-1)*pageSize+1 }}–{{ Math.min(page*pageSize,visibleRows.length) }} de {{ visibleRows.length }}</span><div><button class="pagination-button" @click="page=Math.max(1,page-1)" :disabled="page===1"><ArrowDown class="rotate-up" :size="15"/></button><span class="page-number">{{ page }} / {{ pages }}</span><button class="pagination-button" @click="page=Math.min(pages,page+1)" :disabled="page===pages"><ArrowUp class="rotate-down" :size="15"/></button></div></div></section>
<div v-if="config.adminOnly&&!admin" class="empty-state"><SlidersHorizontal :size="24"/><strong>Acesso restrito</strong><p>Este módulo não está disponível para o seu perfil.</p></div>
<div v-if="modal" class="modal-backdrop" @click.self="modal=false"><section class="form-modal"><header class="modal-header"><div><span class="eyebrow">{{ form.id?'EDIÇÃO':'NOVO CADASTRO' }}</span><h2>{{ config.title }}</h2></div><button class="icon-button" @click="modal=false" aria-label="Fechar"><X :size="18"/></button></header><form @submit.prevent="save"><div class="form-grid"><label v-for="field in config.fields.filter(field => field[0]!=='senha'||!form.id)" :key="field[0]" class="form-field" :class="{'field-wide':field[2]==='textarea'}"><span>{{ field[1] }}<i v-if="!['ativo','clienteId','descricao','categoriaId','fornecedorId','funcionarioId','desconto','taxaEntrega','custoUnitario','dataNascimento','observacoes','cnpj'].includes(field[0])">*</i></span><select v-if="field[2]==='reference'" v-model="form[field[0]]" :required="field[0]!=='clienteId'"><option v-if="field[0]==='clienteId'" value="">Sem cliente vinculado</option><option value="" disabled v-else>Selecione…</option><option v-for="option in referenceOptions[field[0]]||[]" :key="option[field[5]||'id']" :value="option[field[5]||'id']">{{ option[field[4]||'nome'] || option.id }}</option></select><select v-else-if="field[2]==='select'" v-model="form[field[0]]" required><option value="" disabled>Selecione…</option><option v-for="option in field[3]" :key="option" :value="option">{{ option }}</option></select><textarea v-else-if="field[2]==='textarea'" v-model="form[field[0]]" rows="3"/><input v-else-if="field[2]==='checkbox'" v-model="form[field[0]]" type="checkbox"/><input v-else v-model="form[field[0]]" :type="field[2]||'text'" :step="field[2]==='number'?'0.01':undefined" :required="!['ativo','descricao','categoriaId','fornecedorId','clienteId','funcionarioId','desconto','taxaEntrega','custoUnitario','dataNascimento','observacoes','cnpj'].includes(field[0])" :autocomplete="field[0]==='password'||field[0]==='senha'?'new-password':undefined"/></label></div><p v-if="error" class="form-error">{{ error }}</p><div class="modal-actions"><button type="button" class="button-secondary" @click="modal=false">Cancelar</button><button class="button-primary" :disabled="busy"><LoaderCircle v-if="busy" class="spin" :size="16"/><Save v-else :size="16"/> Salvar registro</button></div></form></section></div>
</AppShell></template>
